version: "2"
services:
  plex:
    network_mode: host
    # command: /usr/sbin/start_pms
    build:
      context: ./docker-plex
    # ports:
    #   - "32400:32400"
    #   - "32400:32400/udp"
    #   - "32469:32469"
    #   - "32469:32469/udp"
    #   - "5353:5353/udp"
    #   - "1900:1900/udp"
    volumes:
      - "./data/plex/config:/config"
      - "./data/plex/data:/data"
      - "./data/plex/transcode:/transcode"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - VERSION=latest
      - PUID=1000
      - PGID=1000

  sonarr:
    build:
      context: ./docker-sonarr
    ports:
      - "8989:8989"
    volumes:
      - "./data/sonarr/config:/config"
      - "./data/plex/data/tv:/tv"
      - "./data/sabnzbd/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=1000
      - PGID=1000

  sabnzbd:
    build:
      context: ./docker-sabnzbd
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - "./data/sabnzbd/config:/config"
      - "./data/sabnzbd/downloads:/downloads"
      - "./data/sabnzbd/incomplete-downloads:/incomplete-downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=1000
      - PGID=1000
