version: "2"
services:
  plex:
    # network_mode: "host"
    build:
      context: ./plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    volumes:
      - "./data/plex/config:/config"
      - "./data/plex/data:/data"
      - "./data/plex/transcode:/transcode"
    environment:
      - VERSION=latest
